### PR TITLE
Add test for multiple where directives

### PR DESCRIPTION
**Pull request by cwhitby**
- [x] Added or updated tests
- [ ] Added Docs for all relevant versions
- [ ] Updated the changelog

**Related Issue/Intent**

References #831 

**Changes**

No code changes, only adding a test for applying multiple `@where` directives on the same field

**Breaking changes**

None

### CODE REVIEW

**Comment by spawnia** [comment]
@cwhitby I realized this problem is twofold. While i adapted the handling of `BuilderDirective`'s to allow for multiple builders, the `BaseDirective` does not take into account that there may be more than one directive of the same name.

Thanks for the PR, i am working on a generalized fix.

**Comment by spawnia** [comment]
Actually, the GraphQL specification declares that directives must be unique per location. There is an ongoing RFC to allow repeatable directives: https://github.com/graphql/graphql-spec/pull/472

**Comment by Jofairden** [comment]
@spawnia  you should review this again, as afaik repeatable directives are now officially supported by the spec: https://github.com/graphql/graphql-wg/blob/master/notes/2019-10-10.md#repeatable-directives-ivan-10m

**Comment by spawnia** [comment]
@Jofairden thanks, I am aware. Added support in `graphql-php` for it myself and plan to enable repeatable directives in Lighthouse v5.

**Comment by spawnia** [comment]
@cwhitby the test is working now, since we changed some logic around that makes it function correctly. Also tried your original test [`9a70046` (#834)](https://github.com/nuwave/lighthouse/pull/834/commits/9a7004650c45b2f15c9a576d6a2da7c2f1575159) and got a count of `0`, should be correct?

Merging this for now.

**Pull request merged**
