### PR TITLE
Installation error fix.

### PR DESCRIPTION
**Pull request by kikoseijo**
Got an error after install, 

My suggestion its to publish a demo file if not found with the user model with a login and a create mutation, maybe also a relationship as you got in the v2 roadmap.

Have also added the package auto discovery functionality including the Alias, I think its cool feature.

Does project needs anything else than a initial .graphql file to make a working demo? 
Maybe 1 .graphql with a couple imports?

BTW: as far as I got, your code its crystal clear, congrats!

### CODE REVIEW

**Comment by kikoseijo** [comment]
Regarding initial installation, i suggest to have a publish method (im good at this) and provide use with a query (classical viewer could be good), couple mutations (login + create user), Custom directive (maybe they example regarding related task), missing something?

What you think? Sometimes a working example its better than documentation.

**Comment by SimonErich** [comment]
I think that's an awesome idea.
A good example says a lot of already, without having to write 1000 lines of documentation. Especially if the code changes quickly.
If something doesn't work, I can just check if the example works and copy the approach used there.

**Comment by chrissm79** [comment]
@kikoseijo Thanks for PR!! And an example is a great idea! I'll base it on the walkthrough I created for v1. I'll try to get it up and running tonight or tomorrow afternoon and I'll follow up w/ a link here (as well as #66)

**Comment by kikoseijo** [comment]
I suggest creating the folder structure, based on whats needed now, I guess connections and types folder are not needed, because its tedious to have to create all this folders and if we get an example its easier to duplicate files than got to the docs and find the one. (Probably easier also to maintain them example updates if they belong to the actual project)

Also, if you can provide some working examples ill be able to advance in the implementation a bit faster.

Another thing I end up doing its having a middleware to log request so I can move app development into postman or the playground. Maybe this is something can be embedded as a plus, same thing with the coors, its a must do most of the times.

Doing a bit brainstorm, sorry for the mess of ideas.

BTW: I'm watching this repo, post things anywhere you want, ill get notified.

**Comment by chrissm79** [comment]
@kikoseijo @SimonErich Here's the first iteration of the example project. I'll likely make some updates to it but this should get you started!

**Pull request merged**
