### PR TITLE
Logger added for pusher driver based broadcasting

### PR DESCRIPTION
**Pull request by ssi-anik**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**
Allowing this PR to merge will let developers log the pusher curl requests to the `*.log` file.
https://github.com/illuminate/broadcasting/blob/feb1cb1da7e7670d8fa02220e42581ff99a42d78/BroadcastManager.php#L218-L220

**Breaking changes**
**NOTHING**

### CODE REVIEW

**Comment by spawnia** [comment]
Again, please follow the PR checklist.

**Comment by ssi-anik** [comment]
I am not sure what's wrong in the ci check. my doesn't include any limiting based code. why is showing error in this case?

**Comment by spawnia** [comment]
image

**Comment by ssi-anik** [comment]
- I didn't add any test.
- Didn't document any change.
- I guess changelog is not supposed to be added without adding a tag.

So, am I required to place tick marks in all those boxes even though I didn't do any of thing from the list? If yes, then I'll edit the PR.

**Comment by spawnia** [comment]
Obviously do them first.

**Pull request closed without merging**
