### PR TITLE
Remove dependencies on Facades

### PR DESCRIPTION
**Pull request by 4levels**
Hi @chrissm79,

with the help of ao @kikoseijo I managed to get things working nicely without the need for facades.
As you can see, the changes are quite minimal, I'm just not 100% sure if this won't break anyhting on the Laravel part.

I do already have a workaround in place since Laravel's Passport is also still depending on facades.  The workaround is fairly simpel though: create your own PassportServiceProvider in app/Providers, extending the Laravel Passport service provider and override the offending methods `registerGuard()`, `makeGuard()` and `deleteCookieOnLogout()`. (I've requested the removal of facade calls in Passport months ago but the willingness of the passport team to change this seems very low).

So please feel free to test this in your full laravel projects and I'll be happy to adjust where needed (if needed).

Kind regards,

Erik

### CODE REVIEW

**Comment by kikoseijo** [comment]
Need to check the use of facades for some of the directives.
but im not aware of, so, if @chrissm79  hasn't use Lumen we should explain further.

@4levels solution its to avoid uncomment the `$app->withFacades();`, right?

But, what about `Auth::` isn't a Facade?  we need alternative also if its the case.

for  `$app->withEloquent();`, Eloquent, this is a must use, right?


You know, Lumen comes so minimal thats able to process 1.9k request per second.. by enabling each feature we lower this processing score.. so might me good to try to keep on this philosophy...

**Comment by chrissm79** [comment]
Hey @4levels @kikoseijo, I'm going to try to check this out over the weekend. I've never used lumen before, but I would love to see Lighthouse providing support for it. Hopefully I can wrap my head around some of the edge cases and get a app up and running to test things out with. If all goes well I'll merge this in!! Thanks!!!

**Comment by 4levels** [comment]
Hi @chrissm79,

I'll provide you with the Lumen specific steps to get you up and running quickly with Lumen.  I'll try my best to get this ready today..

I have to admit that working with Lighthouse is a tremendous improvement over manually creating every single type, query, mutation, connection, .. simply amazing!

I'm still struggling with more complex relations but so far no blocking issues here, fantastic project, thanks again for all your effort to get Lighthouse out there!

Erik

**Comment by 4levels** [comment]
Hi @chrissm79 ,

thanks to @kikoseijo and your help I've come to a usable version without depending on Facades.

This PR also addresses some of the Lumen specific requirements (eg. no helpers) by adding them here.

As soon as I have confirmation that the `resolve()` function in `src/GraphQL` is not needed and can be replaced by `app()`, I'll update this PR as well..

**Comment by 4levels** [comment]
Hi @kikoseijo,

you're right, but if I'm not mistaken, app("anyType") will call app()->make("anyType") internally.
You have no idea how happy I am this is working now!  Working with Lighthouse is a real pleasure indeed, just like you told me ;-)

Kind regards,

Erik

**Comment by kikoseijo** [comment]
I know... (From them moment I say the v2 Roadmap and its schema....)

Lighthouse its just what should be, a wrapper that able you to reuse all Laravel (project) classes and functions, and we know after having to rebuild all logic, this beautiful library (Thanks @chrissm79 ), its a pleasure.

**Comment by chrissm79** [comment]
@4levels @kikoseijo Awesome!!! 

@kikoseijo Yes, if there is a way to run the tests in Lumen that would make things a lot easier! I just pulled the travis config off another project but not sure how to get it to run in a Lumen project rather than Laravel.

**Comment by kikoseijo** [comment]
@chrissm79 you very welcome I love it, 
Laravel trap me, then React and finally graphql, I think I have enough technology for the next 5 years,,,
Its been over a year to learn all this bits,, so,, lets get some profit out of it now!


BTW: on last release, should change the first class name to Author, its Comment pulling comment.

**Comment by 4levels** [comment]
Hi @chrissm79 and @kikoseijo,

I'll give the tests some love today and report back here.
@kikoseijo I couldn't agree more, I've added Redux / React Native to the picture as well, to be fully ready for the future..
@chrissm79 The most tempting feature of Lighthouse for me is the ability to have Relay subscriptions working as I see this as the final major step in having a fully featured Relay implementation on top of PHP.

Hope to see this PR merged soon (after I finished checking the tests), I think it really adds to this library to be able to use it without facades and with Lumen ;-)

Thanks again for your great attitudes and help!

Erik

**Comment by 4levels** [comment]
Hi @chrissm79,

I'm just from making the tests run, I had to adjust the DBTestCase file to allow for env settings (see last commit in this PR), read from phpunit.xml since the database name / connection was still hardcoded to `lighthouse`.

So all I needed to do was add some extra variables in the environment section of phpunit.xml, eg:
```xml
        <env name="DB_USERNAME" value="testuser" />
        <env name="DB_PASSWORD" value="testpw" />
        <env name="DB_HOST" value="localhost" />
        <env name="DB_DATABASE" value="testdb" />
```
I'm still checking if I need to adjust some things to run the test suite from a Lumen environment.  I'll keep you posted.  As far as I can see the changes are not breaking anything in the current tests.

**Comment by 4levels** [comment]
Hi @chrissm79,

upon trying to get Lighthouse to work with Lumen, I noticed laravel isn't listed in composer.json
When I compared the requirements with Lumen, I see that only `illumintate/routing` is not in Lumen by default.

I removed all laravel related dependencies and added `laravel/framework` and the tests still go through
```js
    "require": {
        "laravel/framework": "^5.6",
        "opis/closure": "^3.0",
        "webonyx/graphql-php": "^0.11.5"
    },

```

Then I retried after replacing `laravel/framework` with `laravel/lumen-framework`..
```js
    "require": {
        "laravel/lumen-framework": "^5.6",
        "opis/closure": "^3.0",
        "webonyx/graphql-php": "^0.11.5"
    },
```
And all 68 test succeeded as well.

I'm not sure if this guarantees that my fork runs perfectly with Lumen though..
I did a complete removal of `vendor/*` and `composer.lock` to make sure I'm not using old dependencies..

If there's anything else I can / should try, please feel free to ask.

Kind regards,

Erik aka 4levels

**Comment by chrissm79** [comment]
@4levels @kikoseijo Thank you both for all of the work you put in on this one!! I tested it out on my project and everything still works smoothly!

@4levels Sorry I missed your question about subscriptions but I just posted an issue about it (#88)

**Pull request merged**
