### PR TITLE
Fix loading relations with polymorphic parent types

### LINKED ISSUE #1034: MorphOne on Interface/Union returns faulty data
**Describe the bug**
When I try to return data from a `MorphOne` relation using an Interface, the returned data does not match the correct Eloquent model

**Expected behavior/Solution**
Given the following schema:
```graphql
interface Person {
    id: ID!
    user: User! @morphOne
}

union Creator = Employee | Contractor

type User {
    id: ID!
    name: String!
    email: String!
}

type Employee implements Person {
    id: ID!
    position: String!
    user: User! @morphOne
}

type Contractor implements Person {
    id: ID!
    position: String!
    user: User! @morphOne
}

type Color {
    id: ID!
    name: String!
    creator: Creator @morphTo
}

type Query {
    colors: [Color!]! @all
}
```
If I then execute this query:
```graphql
colors {
    id
    name
    creator {
        ... on Person {
            __typename
            id
            user {
                id
                name
                email
            }
        }
    }
}
```
I should be getting the correct `User` for each `user` `MorphOne` relation inside the `creator` union.
However, the same `User` is being returned for **both** `creator`s

**Steps to reproduce**
I've made a fork with a failing test to illustrate this
1. Clone the fork from https://github.com/Gaia-Nutrition/lighthouse
2. Install `docker-compose up -d`
3. Install composer and run test
  - Makefile was not working for me so:
  - Install composer dependencies `docker-compose exec php composer install`
  - Run the failing test: `docker-compose exec php composer test:bug`

**Output/Logs**
Example failing test output:
<details><summary>Click to expand</summary>

```
Failed asserting that an array has the subset Array &0 (
    'data' => Array &1 (
        'colors' => Array &2 (
            0 => Array &3 (
                'id' => '1'
                'name' => 'Jamir Walker'
                'creator' => Array &4 (
                    '__typename' => 'Employee'
                    'id' => '1'
                    'user' => Array &5 (
                        'id' => '1'
                        'name' => 'Alexanne Schroeder'
                        'email' => 'bayer.lacey@example.com'
                    )
                )
            )
            1 => Array &6 (
                'id' => '2'
                'name' => 'Brady Lebsack'
                'creator' => Array &7 (
                    '__typename' => 'Contractor'
                    'id' => '1'
                    'user' => Array &8 (
                        'id' => '2'
                        'name' => 'Ottilie Windler'
                        'email' => 'lincoln70@example.com'
                    )
                )
            )
        )
    )
).
--- Expected
+++ Actual
@@ @@
           'id' => '1',
           'user' =>
           array (
-            'id' => '1',
-            'name' => 'Alexanne Schroeder',
-            'email' => 'bayer.lacey@example.com',
+            'id' => '2',
+            'name' => 'Ottilie Windler',
+            'email' => 'lincoln70@example.com',
           ),
         ),
       ),
```

</details></br>

**Environment**

Lighthouse Version: master
Laravel Version: 6.x

### PR DESCRIPTION
**Pull request by Gaia-Nutrition**
- [x] Added or updated tests
- [x] Added Docs for all relevant versions
- [x] Updated CHANGELOG.md

Resolves #1034 

**Changes**

Fix eager-loading relations where the parent type is an `interface` or `union` and  may correspond to multiple different models.

**Breaking changes**

No

### CODE REVIEW

**Comment by spawnia** [comment]
You can download a diff file from StyleCI and apply that.

**Comment by enzonotario** [comment]
Hi! it's weird, if you change the name of one relation, it works..

**Comment by Gaia-Nutrition** [comment]
That is weird indeed! Also, the problem seems to be the `Union`, not the `Interface`. Do you have some cache here that prevents resolving a relation on a `Union` type more than once?

**Comment by Gaia-Nutrition** [comment]
I totally understand this might not be a priority for everyone but @spawnia or @enzonotario could you point me into a direction so I might be able to help debug this?

**Comment by enzonotario** [comment]
Sorry I don't really know how to fix this. Also I think it is somehow related to #1030 (it's also an issue with `BatchLoader`)

**Comment by enzonotario** [comment]
Hey folks! This issue is also gone setting the new config `batchload_relations` to `false`

**Comment by Gaia-Nutrition** [comment]
But that is more ignoring than solving the problem right?

**Comment by enzonotario** [comment]
Mm I don't think so. Instead of ignoring I think it is just doing every time (not in batch). Maybe it would be more slow and consuming more resources...

**Comment by spawnia** [comment]
Can you change the test to actually run and fail?

**Comment by spawnia** [comment]
I could identify and fix the bug.

Polished tests and docs for the other polymorphic relationships in the process.

**Pull request merged**
