### PR TITLE
[WIP] src + docs = mono repository

### PR DESCRIPTION
**Pull request by robsontenorio**
# Lighthouse Website

Lighthouse website uses [Vue Press](https://vuepress.vuejs.org). A minimalistic [Vue](https://vuejs.org/) powered static site generator. VuePress follows the principle of **"convention is better than configuration"**.

## Branch

https://github.com/robsontenorio/lighthouse/tree/vuepress

## Latest preview (21/11/2019)

https://5bf559de05c4170ceead6d8f--lighthouse-vuepress.netlify.com/

For sure someone can do a better landing page :)

## Directory structure

```bash
# nuwave/lighthouse repository root

docs/
├── .vuepress/            
│   ├── config.js         # global site config
│   └── versions.json     # auto-generated versions file
│
├── master/               
│   ├── guides/         
│   │   └── auth.md       # http://mysite.com/master/guides/auth.html
│   ├── the-basics/         
│   │   └── fields.md     # http://mysite.com/master/the-basics/fields.html
│   │ 
│   └── sidebar.js        # versioned sidebar for this version   
│
├── 2.6/               
│   └── ...               # same structure from "docs/master/"
│
├── pages/
│   └── ...               # Not versioned, it remains the same for all docs versions
│
├── package.json          # vuepress dependencies
└── INDEX.md              # the beauty home page
```

## Run

Make sure you have:

- Node 8+
- Yarn 

Then, start Vue Press on development mode (with hot reloading).
```bash
cd docs/
yarn docs:dev
```

> Keep a eye on console when editing pages. If code can not be compiled for some reason, stop it and start it again Vue Press. Otherwise hot reloading system will hang up.

### Creating new files

1. Place the new file into correspondent version folder.
2. Include the reference for the new file into correspondent `sidebar.js`, according version number.

```bash
# the new file
docs/3.1/guides/cruds.md

# edit the correspondent sidebar
docs/3.1/sidebar.js

```

### Linking files

- Remember to include the `.md` extension. 
- Always use relative paths according to folder structure.

```md
The [@paginate](directives.md#paginate) directive is great!

See the [Tutorial](../getting-started/tutorial.md) for more info.
```

## Versions

Each subfolder in `docs/` will represent a documentation version, except `docs/pages/` that will remain the same for all docs versions. 

| Path                                    | Web route                                           |
|-----------------------------------------|-----------------------------------------------------|
| `docs/master/guides/installation.md`    | `http://mysite.com/master/guides/installation.html` |
| `docs/2.6/guides/installation.md`       | `http://mysite.com/2.6/guides/installation.html`    |
| `docs/pages/users.md`                   | `http://mysite.com/pages/users.html`    |
  
   
### Updating a existent version

You can update multiples docs versions at the same time. Because each `docs/` subfolder represents specifics routes when published.

1. Edit any file.
1. Commit and push changes.
1. It will be published to the correspondent version.

**Example:** When you change any file from `docs/2.6/`, it will publish changes only for `2.6` docs version.

### Tagging a new version

1. First, finsh your work on `docs/master` . A version always should be based from master.

1. Enter a new version number

```bash
yarn docs:version 3.1
```

1. Commit and push.

1. It will be published as the last documentation version.

When tagging a new version, the document versioning mechanism will:

- Copy full `docs/master/` folder contents into a new `docs/<version>/` folder.
- Place a new version number in `docs/.vuepress/versions.json`

### CODE REVIEW

**Comment by chrissm79** [comment]
Hey @robsontenorio, great proposal here and I appreciate you putting in the time to create it! I certainly understand the purpose of having docs inside the same repo as the code. It makes it easier to keep code + docs up to date and allows PRs to be submitted w/ documentation. 

However, I can't say I'm a fan of putting a Node/Vue project inside a PHP package. For instance, the Nova docs mentioned has their documentation in a separate repo (along w/ Laravel itself). Vuepress itself is pretty nice... for one thing the syntax hightlighting for GraphQL actually works 👍(unlike the current version of Docusaurus we have the documentation site running on). Does it support versioning? I didn't find any details on it in the Vuepress site and the Nova docs doesn't seem to have it. If not, I think I'd probably prefer to stay w/ Docusaurus.

If we were able to have `.md` files directly in the root `docs` folder and have the ability to browse through it right inside the GH repo I'd be happy to adopt that solution. But in this scenario, if you're looking at the `/docs/website/docs` folder in the repo and click on the default schema link (in the Scalar section) on [this page](https://github.com/robsontenorio/lighthouse/blob/vuepress/docs/website/docs/the-basics/types.md) it takes you to a 404. So to browse through the documentation you'd have to go to the external docs site.

So I'll leave this in the hands of the community. If you want to open up an issue similar to #417 and have the community vote on 1) Mono Repo vs Separate Repo 2) Vuepress vs Docusaurus, I'll accept the fate of the community 😄

**Comment by spawnia** [comment]
Love the way the vuepress docs look and how the site behaves - super snappy and quick. Search is working as well - so nice job on that!

Links between the docs pages in markdown are not working in docusaurus, so if the vuepress format allows for that, it would be another point in favour of it.

We would have to find a way to do versioning. The docusaurus way is kinda meh, it can be a bit confusing to handle if you want to backport some changes and it does not really add much above just copy-pasting the whole contents into a subfolder. Maybe we can do that automatically whenever a new tag is created?

**Comment by robsontenorio** [comment]
Working right now on basic versioning mechanism and better folder organization. 

In this basic version it will just make a full copy from  “docs/master/” folder and will place it in another folder like “docs/2.6/”. 

Considering the principle of docs versioning it make sense, because we must be able to update very old docs versions. And we must serve online all docs  versions as well. 

I think using git tags won’t work as expected. 

@spawnia @chrissm79 what do you think?

**Comment by spawnia** [comment]
@chrissm79 what is the status on the custom domain for Lighthouse?

**Comment by robsontenorio** [comment]
@spawnia Didn’t touch in theme yet. Finishing versioning mechanism. If you guys agree I can go deeper to a final version.

**Comment by robsontenorio** [comment]
Just finished a finished a basic versioning mechanism and theme styling version 1.

Check the new updated  PR description above.

**Comment by spawnia** [comment]
Hey @robsontenorio, wanted to experiment with a small change on the landing page. How can i see an updated version?

**Comment by robsontenorio** [comment]
https://5bf504dde5cd162b9f1578d7--lighthouse-vuepress.netlify.com

**Comment by robsontenorio** [comment]
@spawnia can you giv a shot locally on versioning system? I am opening a several PR on VuePress repo to place it into core. The current solution is just a workaround, to avoid using a custom VuePress branch.

**Comment by spawnia** [comment]
I might find some time to do that in the weekend.

**Comment by robsontenorio** [comment]
Merged changes and simplify frontpage with flebox

https://5bf559de05c4170ceead6d8f--lighthouse-vuepress.netlify.com/

**Comment by mfn** [comment]
Very nice! (and voted for it in https://github.com/nuwave/lighthouse/issues/433 😄 )

Is it possible to make "already opened nodes" in the left side **not** close when I opened other nodes?

I understand initially it's probably better to hide all nodes though I personally like it when things are "opened" right from the beginning. E.g. top level we've "getting started", "basics" but can we initially render all level 1 open, too? As in:

- Getting started
  - Installation
  - …
- Basics
  - Schema
  - Types
    - foo
- …

**Comment by chrissm79** [comment]
@robsontenorio These docs are coming along quite nicely, great job on all the work!!! The fact that you got linking to work in both GH and the site is pretty outstanding too 👍 

I'm taking a look around the latest build, did the search get disabled? Also, don't put too much effort into the landing page, what you have there is great and I'll be making some tweaks to it anyway.

**Comment by robsontenorio** [comment]
@mfn Yes, it is possible to controll collapsing, with 1 config line.

@chrissm79 Just removed searchbox for a while, because by default it will return duplicated results between docs folder (2.6, 2.7 ...). Just submited a PR to VuePress core.

About landing page I'm done , if you desire it can tweaked with custom css.

**Comment by chrissm79** [comment]
Excellent job on this huge effort @robsontenorio!!! I'm traveling back from vacation today, but I'll try to get the lighthouse-php.com domain (and redirect the old Netlify domain) up today. Thanks!!

**Comment by robsontenorio** [comment]
A side note: before go live the docs must be update from last repo content lighthouse-docs.

**Pull request merged**
