### PR TITLE
Update vuepress to v1.0.2

### PR DESCRIPTION
**Pull request by spawnia**

### CODE REVIEW

**Comment by spawnia** [comment]
@robsontenorio any idea how the build can be fixed? It seems to hang at rendering the Layout:

```
3:40:12 PM: 
3:40:12 PM: Rendering page: /master/the-basics/schema.html
3:40:12 PM: 
3:40:12 PM: Rendering page: /master/the-basics/types.html
3:40:12 PM: 
3:40:12 PM: 
3:40:12 PM: Rendering page: /packages/vuepress-theme-lighthouse/components/Footer.html
3:40:12 PM: 
3:40:12 PM: Rendering page: /packages/vuepress-theme-lighthouse/layouts/Layout.html
4:06:19 PM: Build exceeded maximum allowed runtime
```

**Comment by robsontenorio** [comment]
@spawnia Have you tried locally?

- rm -rf node_modules
- rm yarn.lock
- yarn cache clean
- yarn install

**Comment by spawnia** [comment]
Yup, same issue on `yarn docs:build`. Seems to be related to https://github.com/vuejs/vuepress/issues/966

**Comment by robsontenorio** [comment]
@spawnia Solved by #901 

I would recommend to vetify deployed web site carefully.

**Pull request closed without merging**
