### PR TITLE
Add config option `subscriptions.exclude_empty`

### PR DESCRIPTION
**Pull request by GregPeden**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

Ref: https://github.com/nuwave/lighthouse/issues/1787

**Changes**

Adds config option 'subscriptions.exclude_empty' (default false). When true, and subscriptions are in use, an API response without a channel will exclude the 'lighthouse_subscriptions' extension response as a small performance optimization.

**Breaking changes**

None - default setting 'false' functions the same as before.

### CODE REVIEW

**Comment by GregPeden** [comment]
BTW I added two tests to cover this setting and when I ran the tests my new tests pass but other already existing tests failed. Ran using using the "php" container within the included Docker dev environment.

**Comment by GregPeden** [comment]
eeeek OOOOPS

Wait I wonder why that test didn't trigger as a fail on my end, hmmmmmmmmm........

**Comment by spawnia** [comment]
@GregPeden no idea. Almost there now: https://github.com/nuwave/lighthouse/pull/1799/checks?check_run_id=2355553554

**Comment by GregPeden** [comment]
Oh "foo" returns 42, not null, that's why. Okay I can fix.

I think that I wrote the test but it ran on the code base without the tests, as though the changes weren't saved or something.

**Comment by spawnia** [comment]
Nicely done, thank you.

**Pull request merged**
