### PR TITLE
Prevent name conflict between argument names and non-relation methods when executing nested mutations

### LINKED ISSUE #507: Argument names in nested mutations conflict with non-relation methods on the model
**Describe the bug**
I am using the Spatie Permissions package and there is a 'guard' field on the Role class. When I try to return that field with a query, it will run the Model::guard() method.

**Expected behavior**
Return guard field from the database

**Schema**

```graphql
#types
type Role{
    id: ID!
    name: String!
    guard: String
}

#Inputs
input AddRoleInput {
    name: String! @rules(apply: ["required"])
    guard: String
}

input EditRoleInput {
    id: ID! @rules(apply: ["required"])
    name: String
    guard: String
}

#Add Queries to Base Query
extend type Query {
    roles: [Role!]! @all
    role(id: ID! @eq): Role! @find
}

#Add Mutations to Base Mutation
extend type Mutation {
    addRole(input: AddRoleInput!): Role! @create(flatten: true)
    editRole(input: EditRoleInput!): Role! @update(flatten: true)
    #editRoles(
    #    ids: [ID!]! 
    #    input: EditUsersInput!): [User!]! @bulk(flatten: true)
    deleteRole(id: ID!): Role! @delete
    deleteRoles(id: [ID!]!): [Role!]! @delete
}
```

**Output/Logs**
```
TypeError: Too few arguments to function Illuminate/Database/Eloquent/Model::guard(), 0 passed in /var/www/simple-rmm-appeval()'d code on line 1 and exactly 1 expected
```

**Environment**

Lighthouse Version: 2.6.3
Laravel Version:5.7.16
PHP Version: 7.2.12

**Additional context**

This seems to be the method it is getting caught up on. I'm not sure if there is a way to check if the method exists only on the model child class.
```
    protected static function extractHasManyArgs(Model $model, Collection $args): Collection
    {
        return $args->partition(function ($value, $key) use ($model) {
            return method_exists($model, $key) && ($model->{$key}() instanceof HasMany);
        });
    }
```

### PR DESCRIPTION
**Pull request by liepaja**
- [x] Added or updated tests
- [x] Added or updated docs

**Related Issue/Intent**

Resolves #507

**Changes**

Detect relationships when executing nested mutations by using reflection instead of calling the methods and examining the result.

This prevents non-relationship methods from being called, which may lead to errors and/or side effects.

**Breaking Changes**

Users are required to define the return type of a relationship method in their Eloquent Model for the detection to work.

### CODE REVIEW

**Comment by spawnia** [comment]
I switched the method of detection to what i proposed in the comment.

The approach you chose will fail if a user themselves has defined a method with the same name on the Model.

Another problem it had is that it calls the method, which may lead to side effects.

**Comment by spawnia** [comment]
This seems to fail in PHP 7.0, so we can merge it after we made the switch to require 7.1. #517

**Comment by spawnia** [comment]
@liepaja Please stick to our formatting standard for the docblocks, use `php-cs-fixer`.

**Comment by liepaja** [comment]
Didn't know it was not edited by php-cs-fixer. Reseted

**Comment by spawnia** [comment]
Thanks @liepaja for your contribution.

**Comment by chrissm79** [comment]
Great work on this on @liepaja, thank you!

**Pull request merged**
