### PR TITLE
Generalize ArgFilter to ArgBuilder, enable complex client queries, properly flatten arguments

### LINKED ISSUE #249: Also use flatten (nested queries with input types) for @paginate and @all directive
**Is your feature request related to a problem? Please describe.**
I want to use input types in my `@all` and `@paginate` directives.

**Describe the solution you'd like**
I want to use the `flatten: true` argument from #207 in my `@paginate` and `@all` directive. I tried using it, but it seems that is not yet supported. It would be awesome if I can use the same logic here.

My schema is as follows:
```
type Query {
    addresses(input: whereAddressesInput): [Address]! @all(model: "Address", flatten: true)
}

input whereAddressesInput {String @eq country_code_not: String @not country_code_in: String @in country_code_not_in: String @not_in country_code_lt: String @lt country_code_lte: String @lte country_code_gt: String @gt country_code_gte: String @gte country_code_contains: String @contains country_code_not_contains: String @not_contains country_code_starts_with: String @starts_with country_code_not_starts_with: String @not_starts_with country_code_ends_with: String }
```

_I have shortened the input type in this example, but it should give an idea of how big it actually is when you have 10 columns in your table._

**Describe alternatives you've considered**
Using multiple arguments, but that quicky gets messy when you want to provide a big set of arguments possibilities for every column.

**Additional context**
I have actually tried adding the implementation as in #207 to the directive code, but it appears it's not as easy as adding just this code to the directive:
```
$flatten = $this->directiveArgValue('flatten', false);
$args = $flatten ? reset($args) : $args;
```

@spawnia If you could give some pointers I would be happy to give this a go myself, but for now I'm not comfortable enough with the codebase to know what I'm doing.

### LINKED ISSUE #538: Use all ArgumentDirectives for Input Types
We have Input with something like this

```
input UserFilter {
    id: ID @eq
    name: String @where(operator: "like")
    email: String @where(operator: "like")
}


Using in query like:
type Query {
    users(filter: UserFilter): [User!]! @paginate(type: "paginator")
}
```

Schema by graphql is valid, but directives doesnt work.

**Edit by @spawnia**

Not all directives that can be used on Arguments work on Input Values. Implementation-wise, it is more difficult to handle them, but from a user perspective, there really should not be any difference.

- [x] `@bcrypt`
- [x] `@eq`
- [x] `@in`
- [x] `@neq`
- [x] `@notIn`
~~- [ ] `@rename`~~ (see discussion in #521)
- [x] `@rules`
- [x] `@rulesForArray`
- [x] `@search`
- [x] `@trim`
- [x] `@where`
- [x] `@whereBetween`
- [x] `@whereNotBetween`

### LINKED ISSUE #596: @create and @update flatten parameters do not truly flatten
**Describe the bug**
Currently, CreateDirective, and UpdateDirective use `reset` to flatten the array. Rather than flattening however, this just takes the first element of the array. This causes issues with input types when the ID is specified outside of the input type.

**Expected behavior**
The input passed to the eloquent would include all parameters, flattened.

**Schema**

```graphql
type User {
    id: ID!
    name: String!
}

input UserInput {
    name: String!
}

Mutation {
    # Works, because user is the first field so it passes the UserInput object to eloquent
    createUser(
        user: UserInput!
    ): User @create(flatten: true)

    # Does not work, the only thing that gets passed to eloquent is "int({id})"
    updateUser(
        id: ID!
        user: UserInput!
    ): User @update(flatten: true)
}

```

**Output/Logs**

<details><summary>Click to expand</summary>

```gql
 mutation {
  updateManufacturer(id: 32, manufacturer: {name: "Ryan"}) {
    name
  }
 }
```
```json
{
  "errors": [
    {
      "debugMessage": "No query results for model [Modules\\Inventory\\Entities\\Manufacturer].",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateManufacturer"
      ],
      "trace": [
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/Execution/MutationExecutor.php",
          "line": 92,
          "call": "Illuminate\\Database\\Eloquent\\Builder::findOrFail(null)"
        },
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/Schema/Directives/Fields/UpdateDirective.php",
          "line": 49,
          "call": "Nuwave\\Lighthouse\\Execution\\MutationExecutor::executeUpdate(instance of Modules\\Inventory\\Entities\\Manufacturer, instance of Illuminate\\Support\\Collection(1))"
        },
        {
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\UpdateDirective::Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\{closure}(null, '32', instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 108,
          "function": "call_user_func_array(instance of Closure, array(4))"
        },
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 174,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 781,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 744,
          "call": "GraphQL\\Executor\\Executor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 429,
          "call": "GraphQL\\Executor\\Executor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 446,
          "call": "GraphQL\\Executor\\Executor::GraphQL\\Executor\\{closure}(array(0), 'updateManufacturer', array(0), GraphQLType: Mutation, null, instance of ArrayObject(1))"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php",
          "line": 135,
          "call": "GraphQL\\Executor\\Executor::GraphQL\\Executor\\{closure}(array(0))"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php",
          "line": 35,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::GraphQL\\Executor\\Promise\\Adapter\\{closure}()"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php",
          "line": 140,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()"
        },
        {
          "file": "/var/www/html/backend/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 88,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter::wait(instance of GraphQL\\Executor\\Promise\\Promise)"
        },
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 113,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  updateManufacturer(id: 32, manufacturer: {name: \"Ryangg\"}) {\n    name\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 83,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  updateManufacturer(id: 32, manufacturer: {name: \"Ryangg\"}) {\n    name\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0))"
        },
        {
          "file": "/var/www/html/backend/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 62,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::execute(instance of Illuminate\\Http\\Request)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 682,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/modules/Core/Http/Middleware/Shib.php",
          "line": 39,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Modules\\Core\\Http\\Middleware\\Shib::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 684,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 659,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 625,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 614,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
          "line": 63,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Session\\Middleware\\StartSession::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 31,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 31,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/backend/public-dev/api/index.php",
          "line": 62,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        }
      ]
    }
  ],
  "data": {
    "updateManufacturer": null
  }
}
```

</details></br>

**Environment**

Lighthouse Version: `^2.6`
Laravel Version: `5.7.*`
PHP Version: `^7.2.10`

**Additional context**

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Added Docs for all relevant versions

**ArgFilter flexiblity**

The `ArgFilterDirective` is pretty specific in that it always expects to be setting a query
clause on a single column.

I propose to replace it with the `ArgBuilderDirective` which has a similar but simpler
interface but offers greater flexibility.

**QueryFilter vs. Builder**

The `QueryFilter` class was essentially copied, renamed `Builder` and radically simplified. It is now passed on to resolvers through the `ResolveInfo` instead of requiring a complex instantation process.

**@builder**

Add flexible `@builder` directive to quickly specify a single method to apply constraints
to the query builder, using the given arguments.

I enabled using builders with Input Objects, which allows for more complex client
side query capabilities.

**Argument flattening**

Add `@spread` directive that replaces the `flatten` argument of `@create`/`@update`
and works generally on all input types. Resolves #249

This enables the usage of query manipulating arg directive from within input types, resolves #538

The functionality of `flatten` on `@create`/`@update` was not changed, but was removed from tests
and docs in favour of `@spread`, Resolves #596

**Deprecations**

Plan to remove the `ArgFilterDirective` in v4. Implementors can easily move over to the `ArgBuilderDirective` with little effort.

The `QueryFilter` class will also be removed. This means that directives/resolvers that were utilizing this class to enhance their queries will have to change their API to the new `Builder` class.

Matching two arguments on a single query clause as in `@whereBetween` will no longer possible. The arguments can be passed as an input object or a list now, which gives the same result. I added a config option `new_between_directives` to enable the new behaviour now to allow users to migrate at their own pace.

### CODE REVIEW

**Comment by spawnia** [comment]
@chrissm79 @yaquawa @maarten00 @plunketscott @mfn @SirLamer @websitevirtuoso @NicholasFeldman @sadnub You were all involved in the issues related to this.

The description and the updates to the docs: https://github.com/nuwave/lighthouse/pull/680/files?file-filters%5B%5D=.md should be pretty straightforward to digest, if you want to give this a more thorough review or quick test, that would be great.

Sorry for the size of the PR, the changes were interdependent. I am open to any discussions
for changing the new implementations, namings and APIs.

**Comment by tonipepperoni** [comment]
I think generally a spread directive is more superior than a flatten arg for create etc.

**Comment by spawnia** [comment]
Hey @chrissm79 and everyone else.

I found there were still some issues within the `@whereConstraints` directive, so i left that out for possibly another PR.

Also, i decided i do not want to add breaking changes just yet, so i decided to implement the new functionality alongside the existing filtering logic and mark that for deprecation.

The new `@whereBetween` and `@whereNotBetween` will take a single input object instead of being spread across two args. This behaviour can be enabled now through a feature flag in the config, the existing behaviour will not change until v4.

**Comment by chrissm79** [comment]
@spawnia fantastic work on this one, I’ll get this one reviewed and merged in soon!

**Comment by chrissm79** [comment]
@spawnia Lots of good stuff in here and way more flexible, great job 👍

**Pull request merged**
