### PR TITLE
Support for Apollo Federation

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

Resolves https://github.com/nuwave/lighthouse/issues/911

**Changes**

Allows Lighthouse to function as a federation capable service in Apollo Federation.

**Breaking changes**

No.

### CODE REVIEW

**Comment by tristanpemble** [comment]
hello! I was in the middle of trying to implement Apollo Federation in Lighthouse myself. from what I could tell, there was no good way to extend the webonyx/graphql-php schema printer to handle printing directives due to the use of static methods. I ended up adapting it to write my own. I did not expect to share this, and went a little crazy with generators as an experiment, but it seems to function well. take whatever you need: https://gist.github.com/tristanpemble/f6d427034a33a06392f44ed17fb278dc

**Comment by tristanpemble** [comment]
it would seem the repo linked in the original report has a much simpler [extension of SchemaPrinter](https://github.com/awardis/federation/blob/master/src/Schema/SchemaPrinter.php)

**Comment by spawnia** [comment]
Thank you @tristanpemble, that was some good inspiration :)

**Comment by tristanpemble** [comment]
from what I see most of what is needed for federation is implemented - is there anywhere else I can help (maybe just by testing it out)?

**Comment by spawnia** [comment]
I am not quite sure how to interpret https://www.apollographql.com/docs/federation/federation-spec/#create-stub-types

> A federated service should take the @external fields and types and create them locally so the service can run on its own.

Do we need some kind of mocking / generator?

**Comment by tristanpemble** [comment]
hm. I am definitely not an expert on this, but, I interpret that sentence as leaving the onus on the framework and not on the end-user. I'm not sure how you would automatically mock out types/fields from other federated services if the user did not provide them.

I think the take away from that section could impact this implementation could be here:

> All fields referred to in @key, @requires, and @provides directives need to have corresponding @external fields in the same service.

perhaps you could insert schema validation wrapped in helpful messaging for the library user to tell them they need to define the external type or field in their schema if it is not present.

**Comment by tristanpemble** [comment]
I dug a little deeper on the official JS implementation, I think these validations will help you: https://github.com/apollographql/federation/tree/main/federation-js/src/composition/validate

specifically these are similar to what I was imagining:

- [requiresFieldsMissingExternal.ts](https://github.com/apollographql/federation/blob/main/federation-js/src/composition/validate/postComposition/requiresFieldsMissingExternal.ts)
- [providesFieldsMissingExternal.ts](https://github.com/apollographql/federation/blob/main/federation-js/src/composition/validate/postComposition/providesFieldsMissingExternal.ts)
- [externalUnused.ts](https://github.com/apollographql/federation/blob/main/federation-js/src/composition/validate/postComposition/externalUnused.ts)

I don't fully understand these two:
- [externalMissingOnBase.ts](https://github.com/apollographql/federation/blob/main/federation-js/src/composition/validate/postComposition/externalMissingOnBase.ts)
- [externalTypeMistmatch.ts](https://github.com/apollographql/federation/blob/main/federation-js/src/composition/validate/postComposition/externalTypeMismatch.ts)

anyway, I think digging through their validations will help!

**Pull request merged**
