### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
@robsontenorio looks like we are missing Lumen 8.x to test upon.

**Comment by robsontenorio** [comment]
I will wait for oficial Laravel 8 release. Because actions/composer does not allow minimum stability as “dev”

**Comment by crynobone** [comment]
Hi there, `orchestra/testbench` maintainer here.

Since this package uses `orchestra/testbench` 3.6 and above I would recommend removing `orchestra/database` as all the functionally it available directly from Laravel Framework.

**Comment by plunkettscott** [comment]
Any idea when this will get merged?

**Comment by henzeb** [comment]
I can't find a release date, but version 7 had 13 days in between, so it can be another week before lumen gets released, after that it might take a day or two depending on breaking changes.

**Comment by njaremko** [comment]
They've tagged v8 for lumen: https://github.com/laravel/lumen/releases/tag/v8.0.0

**Comment by stayallive** [comment]
Laravel Scout need a bump to `^7|^8` in the `composer.json` of Lighthouse (and possibly changes for scout 8?).

Scout 8.3 is Laravel 8 compatible.

**Comment by robsontenorio** [comment]
I am late to the party. Nice job @spawnia !

**Comment by spawnia** [comment]
Thanks @robsontenorio for getting this going through your initial PR.

**Pull request merged**
