### PR TITLE
Add `@hash` directive and deprecate `@bcrypt`

### PR DESCRIPTION
**Pull request by Chrissi2812**
- [x] Added or updated tests
- [x] Added Docs for all relevant versions
- [x] Updated CHANGELOG.md

**Changes**

Adds a directive for Laravel's `Hash::make` facade so Lighthouse uses the defined driver of laravel for password hashing, instead of bcrypt via `@bcrypt` directive.

### CODE REVIEW

**Comment by spawnia** [comment]
Can this be done without facades? We generally don't use them because we want to support Lumen, which does not enable them by default.

**Comment by Chrissi2812** [comment]
@spawnia I guess something like this https://stackoverflow.com/a/23574080/6370595 could work. I didn't work with Lumen so I don't know exactly whats supported. 

But what what speaks against adding a hash directive, you already have a bcrypt directive? 
Basically it could just replace the `@bcrypt` directive and you could then configurate the hash directive to use the driver you want (Bcrypt, Argon2i or Argon2id).

**Comment by spawnia** [comment]
I think that adding this directive is a good idea, i just want to see it implement without the use of facades.

**Comment by spawnia** [comment]
Thank you @Chrissi2812 

This will land in the next release, and i will actually replace `@bcrypt` with it in the upcoming major version.

**Pull request merged**
