### PR TITLE
Use a cache key prefix.

### PR DESCRIPTION
**Pull request by Saad89**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**
Use a cache key prefix to generate new cache with every deployment

**Breaking changes**

### CODE REVIEW

**Comment by kingtigg** [comment]
imo this is a great change.

**Comment by spawnia** [comment]
I don't see why that would be necessary, given the cached value is keyed by its hash value. Please explain if there actual is a practical issue you are solving with this, not just a theoretical concern.

**Comment by Saad89** [comment]
> I don't see why that would be necessary, given the cached value is keyed by its hash value. Please explain if there actually is a practical issue you are solving with this, not just a theoretical concern.

- The idea behind this is to have isolated cache for query every deployment.
- An example case a query that have a resolver and cached , Then within next release the query changed with a new the resolver.

**Comment by spawnia** [comment]
I think you do not fully understand what the query cache is, and you do not understand the determistic nature of a hash function. No matter what changes on the server, the query cache stores only documents sent by clients. If the query changes, it will have a different hash.

**Comment by k0ka** [comment]
> An example case a query that have a resolver and cached , Then within next release the query changed with a new the resolver.

Query cache doesn't cache any resolvers. It only caches how a string query (that came from a client) is parsed to an object tree.

**Comment by Saad89** [comment]
> I think you do not fully understand what the query cache is, and you do not understand the determistic nature of a hash function. No matter what changes on the server, the query cache stores only documents sent by clients. If the query changes, it will have a different hash.

Yes, i checked again and it saves only client query at the end.

**Pull request closed without merging**
