### PR TITLE
Add benchmark to measure performance of queries with many results

### PR DESCRIPTION
**Pull request by k0ka**
**Changes**

I've added benchmarks to test GraphQL queries in production-like environment.

### CODE REVIEW

**Comment by spawnia** [comment]
@k0ka nice to see you work on that part of Lighthouse! Please notify me when you get CI to pass 👍

**Comment by k0ka** [comment]
I've fixed the style. And also created the following issue https://github.com/nuwave/lighthouse/issues/1699 with explanation what it tests and why.

I can add another benchmark with all middlewares on to test difference between "default" and "optimized" configurations.

**Comment by spawnia** [comment]
I can confirm a signifant difference depending on the usage of field middleware, for the 10k case:
- none: 0.277
- default: 0.533
- default five times: 1.710

Looks like a great starting point to look into further optimizations!

**Comment by spawnia** [comment]
I am merging this as is, just because it is a nice base to do further performance work. We can definitely still explore what we can do about the global field middleware!

**Pull request merged**
