### PR TITLE
Detect usage of deprecated elements in queries

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
Should use `App::terminating()` for error reporting

**Comment by stayallive** [comment]
Am I understanding correctly that this is just for testing basically? I am unsure what the use of this rule is outside of the testing harnass but maybe I'm missing something 😄

**Comment by spawnia** [comment]
@stayallive I just added some docs. Let me know what you think

**Comment by stayallive** [comment]
Oooooooh. Yes. This is very cool! And really handy 💪

**Pull request merged**
