### PR TITLE
Add support for Laravel 8.0

### PR DESCRIPTION
**Pull request by robsontenorio**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

None.

**Breaking changes**

None.

### CODE REVIEW

**Comment by spawnia** [comment]
Please modify the GitHub actions to run tests on 8.0, too.

**Comment by robsontenorio** [comment]
@spawnia Larave 8 requires minimum PHP 7.3 . Lighthouse support previous Laravel version, wich support 7.2 .
 So, i m not sure how to place actions matrix :(

**Comment by spawnia** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix

**Comment by robsontenorio** [comment]
Will wait for Laravel oficial release.

**Comment by EvilFreelancer** [comment]
Hello! Some time ago was official release of Laravel 8, I've tried lighthouse development edition but seems some features not work, for example middleware directive and programmatic types file (generated by ide helper) is empty.

Any plans for adding support of Laravel 8?

**Comment by robsontenorio** [comment]
@EvilFreelancer Laravel 8 support is available on alpha release only or dev-master.

**Comment by EvilFreelancer** [comment]
@robsontenorio thanks! Hope a stable version will be released soon.

**Pull request closed without merging**
