### PR TITLE
Add test trait `\Nuwave\Lighthouse\Testing\MakesGraphQLRequestsLumen` for usage with Lumen

### PR DESCRIPTION
**Pull request by rafaelmarcelino19**
#1094 
TestResponse is not available in lumen I added this class with the same methods of MakesGraphQLRequests to work in Lumen

### CODE REVIEW

**Comment by spawnia** [comment]
Thanks for the PR, i really appreciate it.

What's preventing us from using a single class for both?

**Comment by spawnia** [comment]
This PR seems to have no changes. Are you planning any?

**Comment by rafaelmarcelino19** [comment]
sorry, i didn't add the changes

**Comment by spawnia** [comment]
> What's preventing us from using a single class for both?

I was actually asking a question here, not necessarily suggesting we should split it. Thanks for giving it a shot, though.

Considering the two approaches, i actually like having separate classes better. Otherwise the helper kind of becomes "worst of both worlds", with watered down type hints and little workarounds. I tried abstracting further and basing both on a single base trait and found that this complicates things even further.

So, i finally settled on your original approach and added the separate trait back in. Tweaked it a little and added docs and a changelog entry. Let me know if that works for you.

**Comment by rafaelmarcelino19** [comment]
for me ok, I thought you didn't want to keep two classes separate, but that would really become "the worst of both worlds"

**Pull request merged**
