### PR TITLE
Enable GET requests to the graphql endpoint when app is in debug mode

### PR DESCRIPTION
**Pull request by hailwood**
Being able to hit the graphql endpoint with a get request is extremely useful for debugging

### CODE REVIEW

**Comment by TGNThump** [comment]
I'd say make this an off-by-default configurable option, or maybe add other options. I run graphql playground as the get request for that endpoint, for example.

**Comment by hailwood** [comment]
@TGNThump it's now off by default.

@olivernybroe I've added a test, unfortunately without creating an entire other test case for a different `getEnvironmentSetUp` there's no way for me to test that you *can't* do a get request if the config key is false and I don't believe it's a big enough issue to justify a new test case. As such we enable the GET option for this test alone and just test it works.

**Comment by olivernybroe** [comment]
@hailwood You can do it with ´app('config')->set('lighthouse.route_enable_get', false);` in the test itself :)

**Comment by hailwood** [comment]
@olivernybroe I actually tried that originally, unfortunately that's too late as by then the server provider that loads the route file has already booted.

**Comment by chrissm79** [comment]
Thanks for submitting this @hailwood!!

**Pull request merged**
