### PR TITLE
Improve cache control directive docs

### PR DESCRIPTION
**Pull request by spawnia**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
We need to revamp the implementation strategy to ensure that root-fields are not cached by default. Instead of implementing `@cacheControl` as `FieldMiddleware´, we could
- listen to the `StartExecution` event
- traverse the AST of the incoming query
- visit every field using `Visitor`
- consider the field's `@cacheControl` settings or apply defaults according to https://www.apollographql.com/docs/apollo-server/performance/caching/#default-maxage

**Comment by mostafa-rz** [comment]
> 



> We need to revamp the implementation strategy to ensure that root-fields are not cached by default. Instead of implementing `@cacheControl` as `FieldMiddleware´, we could
> 
> * listen to the `StartExecution` event
> * traverse the AST of the incoming query
> * visit every field using `Visitor`
> * consider the field's `@cacheControl` settings or apply defaults according to https://www.apollographql.com/docs/apollo-server/performance/caching/#default-maxage
> 
> @mostafa-rz are you willing to take this on?

yes, i will go with it.

**Comment by spawnia** [comment]
Alright, thanks. Please use this branch as the basis for your implementation, I will revert the addition of the previous PR to `master` for now.

**Comment by mostafa-rz** [comment]
> We need to revamp the implementation strategy to ensure that root-fields are not cached by default. Instead of implementing `@cacheControl` as `FieldMiddleware`, we could
> 
> * listen to the `StartExecution` event
> * traverse the AST of the incoming query
> * visit every field using `Visitor`
> * consider the field's `@cacheControl` settings or apply defaults according to https://www.apollographql.com/docs/apollo-server/performance/caching/#default-maxage
> 
> @mostafa-rz are you willing to take this on?

I need some help.

1. The `StartExecution` event is just a parsed incoming request. No directive information inside it thus  `ASTHelper::hasDirective` returns nothing.
2. Is any method or helper exist, which I can give the field and get back the directive information? 
3. What is this `Visitor`?

**Pull request closed without merging**
