### PR TITLE
Allow custom query validation rules selection

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

Resolves https://github.com/nuwave/lighthouse/issues/1486

**Changes**

Allow custom query validation rules selection by rebinding the interface
  `\Nuwave\Lighthouse\Support\Contracts\ProvidesValidationRules`

**Breaking changes**

No

### CODE REVIEW

**Comment by spawnia** [comment]
@genesiscz where would docs for this fit best?

**Comment by genesiscz** [comment]
Wow, this was FAST! Thank you!
What is the best place to place the example provided. AppServiceProvider? Kernel with own provider? Or other place?

**Comment by spawnia** [comment]
Any service provider.

**Comment by genesiscz** [comment]
And vendor service providers which are auto discovered are executed BEFORE the ones configured in the app.php right? Just to be sure

**Pull request merged**
