### PR TITLE
Allow defining default namespaces as an array

### LINKED ISSUE #438: Default model namespaces fail if the model is named like a Facade, e.g. `Log`
**Describe the bug**

Having an Eloquent-Model `Log` (in "App\\Models\\Log"), and querying a single object or a collection of this model, without specifying the `@find`- or `@paginate`-directive with `(models: "App\\Models\\Log")` results in an internal server error. Lighthouse works fine with every other Model except `Log` out of the box.

**Expected behavior**

Resolving the mentioned Model like it does with every other Model out of the box.

**Schema**

```graphql
type Log {
    id: ID!
    context: String!
    created_at: DateTime
    updated_at: DateTime
}

type Query {
  logs: [Log!]! @paginate
  log(id: ID! @eq): Log @find
}
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
{
  "errors": [
    {
      "debugMessage": "Call to undefined method Illuminate\\Log\\Writer::query()",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "log"
      ],
      "trace": [
        {
          "file": "/srv/www/src/api/vendor/nuwave/lighthouse/src/Schema/Directives/Fields/FindDirective.php",
          "line": 43,
          "call": "Illuminate\\Support\\Facades\\Facade::__callStatic('query', array(0))"
        },
        {
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\FindDirective::Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\{closure}(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/srv/www/src/api/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 108,
          "function": "call_user_func_array(instance of Closure, array(4))"
        },
        {
          "file": "/srv/www/src/api/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 174,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 781,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 744,
          "call": "GraphQL\\Executor\\Executor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 473,
          "call": "GraphQL\\Executor\\Executor::resolveField(GraphQLType: Query, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 349,
          "call": "GraphQL\\Executor\\Executor::executeFields(GraphQLType: Query, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 309,
          "call": "GraphQL\\Executor\\Executor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php",
          "line": 59,
          "call": "GraphQL\\Executor\\Executor::GraphQL\\Executor\\{closure}(array(2), array(2))"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 310,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter::create(instance of Closure)"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 166,
          "call": "GraphQL\\Executor\\Executor::doExecute()"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 155,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/srv/www/src/api/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 86,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, '{\n  log(id: 95) {\n    id\n    context\n  }\n}\n', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/srv/www/src/api/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 113,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, '{\n  log(id: 95) {\n    id\n    context\n  }\n}\n', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/srv/www/src/api/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 83,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('{\n  log(id: 95) {\n    id\n    context\n  }\n}\n', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0))"
        },
        {
          "file": "/srv/www/src/api/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 62,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::execute(instance of Illuminate\\Http\\Request)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 212,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 169,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 658,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 102,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 660,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 635,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 601,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 590,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/app/Http/Middleware/LogRouteMiddleware.php",
          "line": 29,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 149,
          "call": "App\\Http\\Middleware\\LogRouteMiddleware::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/barryvdh/laravel-cors/src/HandleCors.php",
          "line": 37,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 149,
          "call": "Barryvdh\\Cors\\HandleCors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 46,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 149,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 102,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/srv/www/src/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/public/index.php",
          "line": 53,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/srv/www/src/api/server.php",
          "line": 21,
          "function": "require_once('/srv/www/src/api/public/index.php')"
        }
      ]
    }
  ],
  "data": {
    "log": null
  }
}
```

</details></br>

**Environment**

Lighthouse Version: 2.6.3
Laravel Version:  5.5.44 (but also with 5.7.13)
PHP Version: 7.1.24

**Additional context**
To solve this problem, it is necessary to add the models attribute to the directives:
```
@paginate(model: "App\\Models\\Log")
@find(model: "App\\Models\\Log")
```

### LINKED ISSUE #439: Allow defining an array of namespaces to try
@sadnub has expressed interest in this feature.

It might be useful/necessary for some users to have classes that belong to the same group of functionality (e.g. Models, Queries) split across multiple namespaces.
The current default namespaces allow defining only one namespace though.

Let's discuss if multiple default namespaces are common enough to warrant the extra complexity and if we want to implement them, how we should go about it.

**Pro's**

- Convenient short definitions
- Enables grouping files by domain instead of function

**Con's**

- Extra complexity in the implementation without actually adding new functionality
- Possible source of bugs/ambiguity when you have the same class in different namespaces
- Goes against the Laravel-like default of grouping files by function, e.g. all Models in one directory

**Points to discuss**

- Should this be possible only for Models or for other default namespaces too?
- Can this only be done in `lighthouse.php` or is it also possible through `@group`?

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Added Docs for all relevant versions

**Related Issue/Intent**

Resolves #438
Resolves #439

**Changes**

From a user perspective, default namespaces can now be defined as singular strings or arrays. See:

```php
    /*
    |--------------------------------------------------------------------------
    | Namespaces
    |--------------------------------------------------------------------------
    |
    | These are the default namespaces where Lighthouse looks for classes
    | that extend functionality of the schema. You may pass either a string
    | or an array, they are tried in order and the first match is used.
    |
    */
    'namespaces' => [
        'models' => ['App', 'App\\Models'],
        'queries' => 'App\\GraphQL\\Queries',
        'mutations' => 'App\\GraphQL\\Mutations',
        'interfaces' => 'App\\GraphQL\\Interfaces',
        'unions' => 'App\\GraphQL\\Unions',
        'scalars' => 'App\\GraphQL\\Scalars',
        'directives' => ['App\\GraphQL\\Directives'],
    ],
```

**Breaking changes**

Nope, existing configurations work as before.

### CODE REVIEW

**Comment by chrissm79** [comment]
@spawnia It's already set to do so. It took a minute for it to push a commit on my PR but it did so automatically

**Comment by spawnia** [comment]
Hm, maybe it does not work for branches in a different repo?

**Comment by chrissm79** [comment]
Current StyleCI setting
screen shot 2018-12-27 at 11 48 01 am

**Comment by chrissm79** [comment]
Could be, it only took a minute on my PR and the branch was created in this repo

**Comment by spawnia** [comment]
I read in the StyleCI docs, i think they will only commit fixes when merging the PR.

For this particular case, i think i will try to manually apply the patch

**Comment by chrissm79** [comment]
Nice work @spawnia 👍

**Pull request merged**
