### PR TITLE
Fix missing route prefix in test url

### LINKED ISSUE #1438: Test GraphQL endpoint generation does not take route prefix in to account
**Describe the bug**

Test GraphQL endpoint generation does not take route prefix in to account when generating. This leads all test requests to responses with 404.

**Solution**

Generating endpoint url using route name.

**Steps to reproduce**

1. Set prefix in route configuration
2. Run a test

### PR DESCRIPTION
**Pull request by milroyfraser**
Resolve #1438

### CODE REVIEW

**Comment by milroyfraser** [comment]
@spawnia I am not sure how to test this properly.  

in `tests/TestCase@getEnvironmentSetUp`
$config->set('lighthouse.route.prefix', 'test-api');

and then

```
class MakesGraphQLRequestsTest extends TestCase
{
    public function testGraphQLEndpointUrl()
    {
        $this->assertEquals($this->graphQLEndpointUrl(), 'http://localhost/test-api/graphql');
    }
}
```

I would like to know your opinion. 

Tnx

**Comment by spawnia** [comment]
@milroyfraser something like that looks fine, sure.

**Comment by spawnia** [comment]
Looks like a test is failing: https://github.com/nuwave/lighthouse/pull/1439/checks?check_run_id=797174555

**Comment by spawnia** [comment]
Thanks, nicely done.

**Pull request merged**
