### PR TITLE
Add method `assertGraphQLErrorMessage()` to `TestResponse` mixin

### PR DESCRIPTION
**Pull request by spawnia**
```php
$this
    ->graphQL(/** @lang GraphQL */ '
    {
        shouldFail
    }
    ')
    ->assertGraphQLErrorMessage('Expected error message.');
```

### CODE REVIEW

**Comment by wimski** [comment]
@spawnia It's nice to see a native method to check for error messages. I used my own trait for this until now. However the current implementation only works if the response contains exactly one error message. I usually have tests where a lot of errors are returned, but I'm only interested in one. This results in the following failure for example:

```json
Unable to find JSON: 

[{
    "errors": [
        {
            "message": "Field MainInput.integer of required type Int! was not provided."
        }
    ]
}]

within response JSON:

[{
    "errors": [
        {
            "message": "Field MainInput.string of required type String! was not provided.",
            "extensions": {},
            "locations": []
        },
        {
            "message": "Field MainInput.integer of required type Int! was not provided.",
            "extensions": {},
            "locations": []
        }
    ]
}].
```

I see two possible solutions. Which of these has your preference?
1. Refactor the current `assertGraphQLErrorMessage` method to pass when multiple errors are present. This would break the situation where people specifically want to test that only one message is present.
2. Add a new `assertGraphQLErrorMessagesContains` method to check if an error message exists among possible multiple. Which could look something like this:

```php
public function assertGraphQLErrorMessagesContains(): Closure
{
    return function (string $message) {
        static::assertContains(
            $message,
            $this->json('errors.*.message')
        );

        return $this;
    };
}
```

**Comment by spawnia** [comment]
@wimski I prefer option 1, asserting that only one error is present does not seem that useful to me. If needed, that can be done by using something like `assertExactJson()` anyways. Can you create a PR?

**Comment by wimski** [comment]
I would love to create a PR (and more besides this one), but as long as the test suite relies on an actual MySQL database instead of the [standard in-memory sqlite 'testing' database](https://packages.tools/testbench/getting-started/configuration.html#in-memory-sqlite-connection), I can't run the test suite and therefore not reliable work on the code.

**Comment by spawnia** [comment]
Have you considered the `docker-compose` based Setup? It comes with the database included. Also, not all tests require a database.

Background info on why we use MySQL for testing: SQLite lacks some features we need to test for.

**Comment by wimski** [comment]
How did I miss the docker file!? 🙈

**Comment by spawnia** [comment]
https://github.com/nuwave/lighthouse/blob/master/CONTRIBUTING.md#setup

**Pull request merged**
