### PR TITLE
Allow additional route configurations `prefix` and `domain`

### PR DESCRIPTION
**Pull request by ddedic**
- [x] Added Docs for all relevant versions
- [x] Updated the changelog
- [x] Added or updated tests

**Changes**

Adds support for graphql route group, so we can use router group specific config like domain, prefix, etc.

**Breaking changes**

None

### CODE REVIEW

**Comment by spawnia** [comment]
Can you give a code example of what you are now able to do that was not possible before?

**Comment by ddedic** [comment]
For example, I´m running GraphQL server on it´s own subdomain, and this allows me to assign domain to route group:
`
    'route' => [
        /*
         * The URI the endpoint responds to, e.g. mydomain.com/graphql.
         */
        'uri' => '/',

        /*
         * Lighthouse creates a named route for convenient URL generation and redirects.
         */
        'name' => 'graphql',

        /*
         * Additional options.
         */
        'prefix' => '',
        'domain' => 'graphql.' . env('APP_DOMAIN', 'localhost'),
        'middleware' => [
            \Nuwave\Lighthouse\Support\Http\Middleware\AcceptJson::class,
        ]
    ],
`

**Comment by spawnia** [comment]
Actually, i just realized that we do not need a route group. Changed the PR, can you check if it still works for you? @ddedic

**Comment by ddedic** [comment]
@spawnia  awesome, works as expected!

**Comment by spawnia** [comment]
Thanks for the contribution!

**Pull request merged**
