### PR TITLE
Support exclude_if and exclude_unless rule

### PR DESCRIPTION
**Pull request by atomita**
- [x] Added or updated tests
~~- [ ] Added Docs for all relevant versions~~
- [x] Updated CHANGELOG.md

**Changes**

Fixed an issue where `exclude_if` or `exclude_unless` rules would not be excluded from args when applied.

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
It looks like the `exclude_if` and `exclude_unless` rules do not only validate the input but also change it.

That seems like a really bad design decision from Laravel, are there any other validation rules that work like this?

**Comment by atomita** [comment]
@spawnia 
There seems to be no other than `exclude_if` and `exclude_unless` at laravel v6.11

**Comment by spawnia** [comment]
I think we might not support this feature of Laravel.

First of all, it just seems wrong to use validation to sanitize incoming data. It should be a discrete mechanism in a different step.

Also, i don't think that masking client errors is a great idea in general. This behaviour is not transparent to clients. Without a description, there is no way for them to know that the argument they passed is going to be ignored. If the backend ever changes, there is no way for the client to know.

In terms of implementation, changing the incoming data in a validation step breaks some assumptions that Lighthouse currently makes. We would have to go out of our way to support this, for instance, we would also need to mutate the `ArgumentSet` - a data structure that holds the passed argument values and their types.

**Comment by atomita** [comment]
@spawnia 
I'm sad, but I understand.

**Comment by spawnia** [comment]
Thank you for your contribution and your understanding. Please don't let this discourage you, your PR certainly was well done and i very much welcome future contributions.

I mentioned the fact that those rules are not supported in the directive definition, i am glad you brought it up: https://github.com/nuwave/lighthouse/pull/1168. I hope the added section about sanitization helps you.

**Pull request closed without merging**
