### PR TITLE
Eager-load the subscription fields to ensure they are registered

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Added Docs for all relevant versions
- [x] Updated the changelog (Not necessary, as this just fixes something that was broken inbetween releases)

**Related Issue/Intent**

Resolves https://github.com/nuwave/lighthouse/issues/851

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
Not sure if that resolves the issue. I would be happy if someone can chime in with an (automated) test :)

**Comment by alberthaff** [comment]
I'll do some manual testing tomorrow... 👍

**Comment by alberthaff** [comment]
@spawnia Everything seems to work! I have not tested with inline broadcasts yet.

**Comment by spawnia** [comment]
Those are the ones that worry me the most. If you can come up with a test, you can commit it directly to this branch.

**Comment by spawnia** [comment]
Thanks so much @alberthaff, nice job on that test! Looks really clean

**Pull request merged**
