### PR TITLE
Fix PHPUnit 8 depreciation warnings.

### PR DESCRIPTION
**Pull request by lucasmichot**
- [ ] Added or updated tests
- [ ] Added Docs for all relevant versions

**Related Issue/Intent**

Fix PHPUnit 8 depreciation warnings.

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
Oops, shouldn't have merged that.

**Comment by lucasmichot** [comment]
😭

**Comment by spawnia** [comment]
Sorry @lucasmichot, doing great work!

**Comment by lucasmichot** [comment]
I's OK, another PR comes

**Comment by spawnia** [comment]
Will merge as it is ready

**Pull request merged**
