### PR TITLE
[FIX] Interfaces not providing possible types

### PR DESCRIPTION
**Pull request by chrissm79**
**PR Type**

Bugfix

**Changes**

Currently just a test to show that interfaces do not provide a `possibleType`

**Breaking changes**

None (at the moment)

### CODE REVIEW

**Comment by spawnia** [comment]
This seems like it could be a bug in webonyx

**Comment by chrissm79** [comment]
@spawnia I'm starting to come to that conclusion as well.

**Comment by chrissm79** [comment]
Created an issue upstream (will try to add a PR w/ a failing test there as well)

https://github.com/webonyx/graphql-php/issues/355

**Comment by spawnia** [comment]
Let's integrate the Schema into our TypeRegistry. Having the types in both is wasteful.

**Comment by chrissm79** [comment]
yep, agreed

**Comment by chrissm79** [comment]
@spawnia actually, i may have gotten ahead of myself here... won't we run into a circular reference issue if we don't have a [registry](http://webonyx.github.io/graphql-php/type-system/object-types/#recurring-and-circular-types) that holds references to the type instances?

**Comment by spawnia** [comment]
I have an idea for that in mind. Am on mobile right now so i can not type it out fully. I will get back to this in a few hours, hang tight in the meantime

**Comment by chrissm79** [comment]
@spawnia Since this is a quick hotfix I'm going to merge this one in but create a new refactor PR and make any updates to the TypeRegistry there and we'll get it merged in. Thanks!!

**Pull request merged**
