### PR TITLE
Add tests and fixes to ensure Query and Mutation fields are treated equally

### PR DESCRIPTION
**Pull request by spawnia**
Enhanced the existing tests and added an additional test for nested Inputs, that were previously only considered on Mutations.

Changed the implementation so that no difference is made between queries and mutations.

### CODE REVIEW

**Comment by chrissm79** [comment]
So what should happen if we add the following test to `RuleFactoryTest`?

```php
/**
  * @test
  */
public function itCanGenerateRulesForQueryArguments()
{
    $documentAST = ASTBuilder::generate('
    type User {
        email: String @rules(apply: ["required", "email"])
    }
    type Query {
        user(foo: String @rules(apply: ["required"])): User
    }');

    $variables = [
        'input' => [
            'email' => 'foo',
        ],
    ];

    $rules = (new RuleFactory())->build(
        $documentAST,
        $documentAST->objectTypeDefinition('Query'),
        $variables,
        'createUser'
    );

    // $rules is empty...
}
```

**Comment by spawnia** [comment]
````php
$this->assertSame([
	'foo' => ['required']
], $rules);
````

**Comment by spawnia** [comment]
Was the rule on a field you put intended?

**Comment by chrissm79** [comment]
No you pushed an update that I hadn't pulled down :-)

**Pull request merged**
