### PR TITLE
PR test code for 3 level of depth in relationship

### PR DESCRIPTION
**Pull request by subhankhalid402**
i want to insert data in different tables in nested mutation. Like, first user creation, then add lead data of that user that is created. And then add entry in pivot table of agent_task, in which i want to put lead_id that is recently created. And then i want to add row to another table where i want to use the id of agent_task that is recently created.

- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
Good start. Next, the test should actually do something. So models, tables etc. need to be in place.

**Comment by subhankhalid402** [comment]
> Good start. Next, the test should actually do something. So models, tables etc. need to be in place.

where to upload models? and tables?

**Comment by spawnia** [comment]
- https://github.com/nuwave/lighthouse/tree/master/tests/Utils/Models
- https://github.com/nuwave/lighthouse/tree/master/tests/database/migrations

**Comment by subhankhalid402** [comment]
> * https://github.com/nuwave/lighthouse/tree/master/tests/Utils/Models
> * https://github.com/nuwave/lighthouse/tree/master/tests/database/migrations

upload files feature is disabled.

**Comment by spawnia** [comment]
> upload files feature is disabled.

I am not sure what is supposed to mean. Just create the files in your fork of this repository, commit and push.

**Comment by subhankhalid402** [comment]
> > upload files feature is disabled.
> 
> I am not sure what is supposed to mean. Just create the files in your fork of this repository, commit and push.

okay

**Comment by subhankhalid402** [comment]
> * https://github.com/nuwave/lighthouse/tree/master/tests/Utils/Models
> * https://github.com/nuwave/lighthouse/tree/master/tests/database/migrations

models and migrations added.

**Comment by spawnia** [comment]
Please close all PRs but this one and add all the files to this branch https://github.com/subhankhalid402/lighthouse/tree/patch-1

**Comment by subhankhalid402** [comment]
> Please close all PRs but this one and add all the files to this branch https://github.com/subhankhalid402/lighthouse/tree/patch-1

done

**Comment by subhankhalid402** [comment]
> Please close all PRs but this one and add all the files to this branch https://github.com/subhankhalid402/lighthouse/tree/patch-1

Let me know if anything more needed.

**Comment by spawnia** [comment]
Looks like the test setup is severely broken: https://github.com/nuwave/lighthouse/pull/1477/checks?check_run_id=877419042

Please make sure that your new test fails and the rest of the tests still work.

**Comment by subhankhalid402** [comment]
> Looks like the test setup is severely broken: https://github.com/nuwave/lighthouse/pull/1477/checks?check_run_id=877419042
> 
> Please make sure that your new test fails and the rest of the tests still work.

some of the files are already present in repository like 
Models: User, Task
Migrations: users, tasks etc

what to do with these???

**Comment by spawnia** [comment]
The goal of the testsuite is to provide realistic test cases and ensure Lighthouse works correctly. Try to fit a representative example for your use case in with the existing test files. You can add fields as needed or create new tables and new models.

**Comment by subhankhalid402** [comment]
> The goal of the testsuite is to provide realistic test cases and ensure Lighthouse works correctly. Try to fit a representative example for your use case in with the existing test files. You can add fields as needed or create new tables and new models.
> 
> Modify the repository in such a way that existing test cases still work, and your use case is also represented, producing one or more failing tests that will pinpoint the issue within Lighthouse.

my test case has 2 same models, and tables. and because of these are already exists in repository, therefore not compatible.

**Comment by spawnia** [comment]
> my test case has 2 same models, and tables. and because of these are already exists in repository, therefore not compatible.

Than adapt your test case to make it fit within the repo. Surely a 1-1 copy of your exact setup is not needed.

**Pull request closed without merging**
