### PR TITLE
Allow querying for null values using `@whereConstraints`

### PR DESCRIPTION
**Pull request by jakesyl**
Null values are completely valid within graphql

- [x] Added or updated tests
- [x] Added Docs for all relevant versions
- [x] Updated the changelog

**Related Issue/Intent**

#799 (sort of) and https://lighthouse-php.slack.com/archives/CB28A070S/p1563765389011100:

Screen Shot 2019-07-21 at 11 19 37 PM

**Changes**

Allows `WhereDirective` to query for null values

**Breaking changes**
None

### CODE REVIEW

**Comment by olivernybroe** [comment]
Nice work! 
I'll say this is breaking change as maybe somebody is used to it failing on null and actually have code that depends on that. 

I however totally agree with the changes to allow null in it.

**Comment by jakesyl** [comment]
@olivernybroe, I see your point, but the failure on null isn't documented behavior. 

Perhaps we can merge this into the next version? Because this isn't documented behavior I'd consider this a bug

**Comment by spawnia** [comment]
I think the code is fine as is, and will allow you to pass `null` as a value. The `column` can not be null, however.

You can prove me wrong with a failing test ;)

**Comment by jakesyl** [comment]
@spawnia on it :)

**Comment by jakesyl** [comment]
Ah @spawnia, Actually I think your misconception is when a passed in variable is null.

**Comment by spawnia** [comment]
Can you please add a test case to this PR that shows the current faulty behaviour and how it is fixed by this change?

**Comment by spawnia** [comment]
Nice job on the failing test. Removing the check altogether is too much though, added in a test to show why it's there.

**Comment by jakesyl** [comment]
Thanks! Missed that one.

**Comment by spawnia** [comment]
Turns out `isset` returns false when the value is `null`. `array_key_exists` does what i intended.

**Comment by jakesyl** [comment]
image

Need to wait for the CI, but showing green on my end now :).

**Pull request merged**
