### PR TITLE
Add Apollo federation support to GraphQL implementation

### LINKED ISSUE #911: Support for Apollo Federation
[Issuehunt badges](https://issuehunt.io/r/nuwave/lighthouse/issues/911)

A while ago Apollo introduced a new strategy for merging GraphQL schemas together in a more sensible way than schema stitching. It would be great to see this supported in Lighthouse too.

https://www.apollographql.com/docs/apollo-server/federation/introduction/
https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/nuwave/lighthouse/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by renepardon**
- [ ] Added or updated tests
- [ ] Added Docs for all relevant versions
- [x] Updated CHANGELOG.md

Resolves #911

**Changes**

Implementation of federation specification as described here:

- https://www.apollographql.com/docs/apollo-server/federation/introduction/
- https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

**Breaking changes**

### CODE REVIEW

**Comment by renepardon** [comment]
Currently blocked by https://github.com/webonyx/graphql-php/issues/552 as it is not an option to copy the SchemaPrinter into lighthouse just to "extend" it.

**Comment by jerredhurst** [comment]
@spawnia - Is there a way to help in https://github.com/webonyx/graphql-php/issues/552 so this can keep moving forward?

**Comment by spawnia** [comment]
@jerredhurst my favorite approach would be to add an option to their printer to print directives.

If that is not possible, we can go ahead and implement the simplest possible approach to solve our specific use case. Maybe we can find a way to make the `SchemaPrinter` extensible enough so we can reuse some of its logic?

**Comment by jerredhurst** [comment]
@spawnia - Thank you for the response.  In regards to your comment:

> my favorite approach would be to add an option to their printer to print directives.

Have you implemented this in other cases?  Is there something we can see?

**Comment by spawnia** [comment]
@renepardon thanks for the effort, too bad you moved on.

Closing this PR, i pulled in the changes to a branch: https://github.com/nuwave/lighthouse/tree/federation

**Pull request closed without merging**
