### PR TITLE
Fix cache key when the user is not authenticated

### PR DESCRIPTION
**Pull request by hosmelq**
- [x] Added or updated tests
- [x] Added Docs for all relevant versions
- [x] Updated the changelog

**Related Issue/Intent**

`@cache(private: true)` fails when the user is not authenticated.

**Changes**

Check if the user is authenticated before create the cache key.

**Breaking changes**

None

### CODE REVIEW

**Comment by spawnia** [comment]
@hosmelq i am interested in the use case this solves. Can you give an example of when you would want this behaviour?

**Comment by hosmelq** [comment]
This is my schema.

```graphql
type User {
  id: ID!
  ...
}

type Game {
  id: ID!
  viewerIsAMember: Boolean!
    @field(resolver: "App\\GraphQL\\Types\\Game@viewerIsAMember")
    @cache(maxAge: 300 private: true)
  ...
}
```

The `viewerIsAMember` field identifies if the authenticated user is part of the game but this game is accessible for not authenticated users too, for that reason I'm getting the error.

**Comment by spawnia** [comment]
Makes sense. Can you add a test case?

**Comment by spawnia** [comment]
Thanks @hosmelq nice job.

**Pull request merged**
