### PR TITLE
Allow ScoutBuilder in @paginate directive

### PR DESCRIPTION
**Pull request by arrisar**
An issue was not raised, as it seemed simpler to fix the issue.

Introduce in [this commit](https://github.com/nuwave/lighthouse/commit/6a9b5ac971edeef9a5b142d73902a5d4197b04c4), directive types were more strictly asserted. Causing the ScoutBuilder to be an invalid type in some directives.

While this PR only fixes this directive, it is likely there are others.

**Changes**

This PR _very_ simply allows the ScoutBuilder as a valid Builder type in the `@paginate` directive.

**Breaking changes**

None.

### CODE REVIEW

**Review by rickardw — COMMENTED** [review]
LGTM

**Comment by spawnia** [comment]
Most other directives won't work, since the `ScoutBuilder` is very limited in its capabilities.

**Comment by spawnia** [comment]
Static analysis fails, the critical error is this:

```
Parameter #1 $builder of method                                        
         Nuwave\Lighthouse\Execution\Arguments\ArgumentSet::enhanceBuilder()    
         expects                                                                
         Illuminate\Database\Eloquent\Builder|Illuminate\Database\Eloquent\Rel  
         ations\Relation|Illuminate\Database\Query\Builder,                     
         Illuminate\Database\Eloquent\Builder|Illuminate\Database\Eloquent\Rel  
         ations\Relation|Illuminate\Database\Query\Builder|Laravel\Scout\Build  
         er given.
```

Try widening the expected type in `Nuwave\Lighthouse\Execution\Arguments\ArgumentSet::enhanceBuilder()` and see if the following code is ready to handle a `ScoutBuilder`.

**Comment by pyrou** [comment]
Any update on this ?
We are currently stuck on lighthouse 5.45 because of this issue.

**Pull request closed without merging**
