### PR TITLE
Use $user from Context instead of app('auth')

### PR DESCRIPTION
**Pull request by TGNThump**

### CODE REVIEW

**Comment by chrissm79** [comment]
@TGNThump I originally was going to go this way but the main issue is that the `Context` can be customized and the user may choose to set the authorized user as `$context->auth` instead of `$context->user`... I didn't really think about it until I created context drivers for the subscriptions package. I think the `app('auth')` should probably stay to keep things safe.

**Comment by TGNThump** [comment]
@chrissm79 Then I'd suggest allowing the user to customize what guard lighthouse pulls the user from.

**Comment by chrissm79** [comment]
@TGNThump That sounds like a good idea! I can add a `guard` argument to the `auth` directive

**Comment by spawnia** [comment]
Seems like this PR is superseded by the changes in https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/Fields/AuthDirective.php

**Pull request closed without merging**
