### PR TITLE
Fix overly eager validation of repeatable directive usage

### PR DESCRIPTION
**Pull request by spawnia**
Requires `webonyx/graphql-php:^14.6.2`, see https://github.com/webonyx/graphql-php/pull/848

### CODE REVIEW

**Review by stayallive — DISMISSED** [review]
Need to check it a little better

**Comment by spawnia** [comment]
> Need to check it a little better

Is the fix working for you?

**Review by stayallive — APPROVED** [review]
YES! This works ❤️

**Comment by wimski** [comment]
I think this broke the use of closures in validation.

```php
<?php

use Nuwave\Lighthouse\Validation\Validator;

class MyInputValidator extends Validator
{
    public function rules(): array
    {
        return [
            'my_field' => [
                function (string $attribute, $value, Closure $fail) {
                    // do some custom validation and call $fail when needed
                },
            ],
        ];
    }
}
```

This returns the following error on a request.

```json
[{
    "errors": [
        {
            "debugMessage": "strpos() expects parameter 1 to be string, object given",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 3,
                    "column": 17
                }
            ],
            "path": [
                "myRequest"
            ],
            "trace": [
                {
                    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php",
                    "line": 233,
                    "function": "strpos(instance of Closure, ':')"
                },
                {
                    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php",
                    "line": 201,
                    "call": "Illuminate\\Validation\\ValidationRuleParser::parseStringRule(instance of Closure)"
                },
                {
                    "file": "/var/www/html/vendor/nuwave/lighthouse/src/Validation/RulesGatherer.php",
                    "line": 235,
                    "call": "Illuminate\\Validation\\ValidationRuleParser::parse(instance of Closure)"
                },
                ...
            ]
        }
    ]
}]
```

**Comment by wimski** [comment]
https://github.com/nuwave/lighthouse/pull/1831

**Pull request merged**
